### ISSUE TITLE
Invalid Example: AutocompleteComponent do not exists

### ISSUE THREAD

**Issue by bclermont** [ErrorPro/react-google-autocomplete#130]
https://github.com/ErrorPro/react-google-autocomplete/blob/59ac59eb48ef817b2f79167ac1a6a03c74552a74/docs/examples.js#L70 refers to a name that do not exists in the repository

```console
/workspace/node_modules/react-google-autocomplete $ find . -type f | xargs grep AutocompleteComponent
./docs/examples.js:              <AutocompleteComponent
```

**Comment by ErrorPro** [comment]
Those are meant more as pseudocode rather than something you could run and play yourself. It'd be nice to have some kinda example that you can run(provide your token) and play with it though. Due to lack of time something I cannot do atm but definitely something we will look into in the future. Thanks for letting us know!

**Comment by ErrorPro** [comment]
Let me know if you have time/will to make it real :)
