### ISSUE TITLE
remove default value for types props 

### ISSUE THREAD

**Issue by subzekt** [ErrorPro/react-google-autocomplete#26]
is there any rationale behind making the types props to be defaulted to (cities)? Can it not me made optional like bounds and componentRestrictions

I recently stumbled upon a requirement that allows me to consider all the autocomplete suggestions
According to google docs, 

> If nothing is specified, all types are returned

[https://developers.google.com/places/web-service/autocomplete#place_types](url)

**Edit : I can make it work using this code block, passing the types as empty array**

```import Autocomplete from 'react-google-autocomplete';

<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      console.log(place);
    }}
    types={[]}
    componentRestrictions={{country: "ru"}}
/>

**Comment by subzekt** [comment]
`import Autocomplete from 'react-google-autocomplete';

<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      console.log(place);
    }}
    types={[]}
    componentRestrictions={{country: "ru"}}
/>`
I can get away with using this code block

**Comment by ErrorPro** [comment]
@subzekt I can make it to be optional, by default it will be an empty array, but I would not like to do so because it might break somebody's applications or logic. You can always pass an empty array yourself, or even write a wrapper for this `<MyWrappedAutocomplete {...this.props} />` and your wrapper would do this `<Autocomplete types={[]} {...this.props} />`. Is it really crucial for you?

**Comment by ErrorPro** [comment]
I'm about to update this lib to the next version and there's a list of improvements you would like to see https://github.com/ErrorPro/react-google-autocomplete/issues/14. There's not many of them atm but if there are I will update this lib.

**Comment by subzekt** [comment]
@ErrorPro Thanks for the library. This  is not so crucial for me
