### ISSUE TITLE
React Ref Issue

### ISSUE THREAD

**Issue by alexmarmon** [ErrorPro/react-google-autocomplete#39]
With the most recent version @1.0.17, we are seeing a new error pop up:
```
Uncaught TypeError: Cannot set property 'autocomplete' of undefined
```

Without diving in too much it looks like the ref on line 41 of index.js isn't being set or accessed properly. Any help would be fantastic.

**Comment by ErrorPro** [comment]
@alexmarmon Thanks, will check it today

**Comment by ErrorPro** [comment]
Ok guys, I've just checked the code and it seems to work for me. I've published a fix for it, basically just checking if this.refs is accessible but please fill free to dive into the problem and see what causes it. Otherwise I need more info about browser/environment where the error occurred in. Cheers.

**Comment by ErrorPro** [comment]
@alexmarmon can you check the latest version please?

**Comment by alexmarmon** [comment]
@ErrorPro Looks like the error is gone. Thank you for the help! If it pops back up or we come across the root cause I'll be sure to let you know.
